server.port=8080

# H2 Database settings
spring.datasource.url=jdbc:h2:mem:skillversedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Show SQL queries
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
